import { Place } from "./types";

export const SAMPLE_PLACES: Place[] = [
  {
    id: "golden-steamer",
    name: "Golden Steamer",
    category: "food",
    subcategory: "Chinese",
    address: "143 Mott St",
    neighborhood: "Chinatown",
    description:
      "Famous for fluffy pork buns and classic Cantonese steamed buns. Cheap, fast, and always busy.",
    price_tier: 1,
    avg_price: 5,
    tags: ["dim-sum", "cheap-eats", "cash-friendly"],
    lat: 40.7173,
    lng: -73.9973,
    status: "approved",
  },
  {
    id: "spicy-village",
    name: "Spicy Village",
    category: "food",
    subcategory: "Chinese",
    address: "68 Forsyth St",
    neighborhood: "Chinatown",
    description:
      "Henan-style cuisine. Known for the Big Tray Chicken and hand-pulled noodles.",
    price_tier: 1,
    avg_price: 12,
    tags: ["noodles", "spicy", "local-favorite"],
    lat: 40.717,
    lng: -73.9935,
    status: "approved",
  },
  {
    id: "los-tacos-no-1",
    name: "Los Tacos No. 1",
    category: "food",
    subcategory: "Mexican",
    address: "Chelsea Market",
    neighborhood: "Chelsea",
    description:
      "Arguably the best tacos in NYC. Adobada and carne asada are must-orders.",
    price_tier: 1,
    avg_price: 4,
    tags: ["tacos", "fast", "iconic"],
    lat: 40.7423,
    lng: -74.006,
    status: "approved",
  },
  {
    id: "los-mariscos",
    name: "Los Mariscos",
    category: "food",
    subcategory: "Mexican Seafood",
    address: "Chelsea Market",
    neighborhood: "Chelsea",
    description:
      "Seafood sister spot to Los Tacos. Famous for fish tacos and ceviche.",
    price_tier: 2,
    avg_price: 15,
    tags: ["seafood", "tacos"],
    lat: 40.7423,
    lng: -74.006,
    status: "approved",
  },
  {
    id: "arepas-cafe",
    name: "Arepas Cafe",
    category: "food",
    subcategory: "Venezuelan",
    address: "33-03 36th Ave",
    neighborhood: "Astoria",
    description:
      "Authentic Venezuelan arepas, pabellón, and cachapas. Cozy and flavorful.",
    price_tier: 1,
    avg_price: 12,
    tags: ["arepas", "latin", "comfort-food"],
    lat: 40.757,
    lng: -73.924,
    status: "approved",
  },
  {
    id: "wah-fung",
    name: "Wah Fung",
    category: "food",
    subcategory: "Chinese",
    address: "79 Chrystie St",
    neighborhood: "Chinatown",
    description:
      "Legendary roast pork and duck over rice. Huge portions for cheap.",
    price_tier: 1,
    avg_price: 8,
    tags: ["bbq", "cheap-eats"],
    lat: 40.7176,
    lng: -73.9937,
    status: "approved",
  },
  {
    id: "a-a-bake",
    name: "A & A Bake Doubles and Roti",
    category: "food",
    subcategory: "Caribbean",
    address: "1337 Fulton St",
    neighborhood: "Bed-Stuy",
    description:
      "Famous Trinidadian doubles and roti. One of NYC’s best Caribbean spots.",
    price_tier: 1,
    avg_price: 6,
    tags: ["doubles", "roti", "street-food"],
    lat: 40.6806,
    lng: -73.9472,
    status: "approved",
  },
  {
    id: "b-h-dairy",
    name: "B & H Dairy",
    category: "food",
    subcategory: "Deli",
    address: "127 2nd Ave",
    neighborhood: "East Village",
    description:
      "Old-school kosher dairy counter. Known for pierogies, latkes, and soups.",
    price_tier: 1,
    avg_price: 10,
    tags: ["classic", "comfort-food"],
    lat: 40.7285,
    lng: -73.9874,
    status: "approved",
  },
  {
    id: "lindustrie",
    name: "L'Industrie Pizzeria",
    category: "food",
    subcategory: "Pizza",
    address: "254 S 2nd St",
    neighborhood: "Williamsburg",
    description: "Top-tier NYC pizza with burrata slices and perfect crust.",
    price_tier: 2,
    avg_price: 6,
    tags: ["pizza", "artisan"],
    lat: 40.7115,
    lng: -73.9666,
    status: "approved",
  },
  {
    id: "mamouns",
    name: "Mamoun’s Falafel",
    category: "food",
    subcategory: "Middle Eastern",
    address: "119 MacDougal St",
    neighborhood: "Greenwich Village",
    description: "NYC institution for cheap falafel sandwiches since 1971.",
    price_tier: 1,
    avg_price: 5,
    tags: ["falafel", "cheap", "late-night"],
    lat: 40.7301,
    lng: -73.9986,
    status: "approved",
  },
  {
    id: "raku",
    name: "Raku",
    category: "food",
    subcategory: "Japanese",
    address: "48 MacDougal St",
    neighborhood: "SoHo",
    description: "Authentic udon spot. Handmade noodles and late-night hours.",
    price_tier: 2,
    avg_price: 18,
    tags: ["udon", "japanese"],
    lat: 40.7283,
    lng: -74.0003,
    status: "approved",
  },
  {
    id: "woorijip",
    name: "Woorijip",
    category: "food",
    subcategory: "Korean",
    address: "12 W 32nd St",
    neighborhood: "Koreatown",
    description:
      "Cheap Korean buffet-style takeaway. Tons of options under $10.",
    price_tier: 1,
    avg_price: 9,
    tags: ["korean", "buffet", "cheap"],
    lat: 40.7477,
    lng: -73.9866,
    status: "approved",
  },
  {
    id: "hamburger-america",
    name: "Hamburger America",
    category: "food",
    subcategory: "Burgers",
    address: "51 MacDougal St",
    neighborhood: "SoHo",
    description:
      "George Motz’s classic American burger joint. Smashburgers done right.",
    price_tier: 2,
    avg_price: 12,
    tags: ["burgers", "classic"],
    lat: 40.7286,
    lng: -74.0002,
    status: "approved",
  },
  {
    id: "food-gallery-32",
    name: "Food Gallery 32",
    category: "food",
    subcategory: "Food Court",
    address: "11 W 32nd St",
    neighborhood: "Koreatown",
    description:
      "Korean food hall with a wide variety of stalls and cheap eats.",
    price_tier: 1,
    avg_price: 10,
    tags: ["food-hall", "variety"],
    lat: 40.7476,
    lng: -73.9865,
    status: "approved",
  },
  {
    id: "shu-jiao-fu-zhou",
    name: "Shu Jiao Fu Zhou",
    category: "food",
    subcategory: "Chinese",
    address: "295 Grand St",
    neighborhood: "Chinatown",
    description: "Peanut noodles and dumplings for under $5. Absolute classic.",
    price_tier: 1,
    avg_price: 4,
    tags: ["dumplings", "cheap"],
    lat: 40.7166,
    lng: -73.9899,
    status: "approved",
  },
  {
    id: "birria-landia",
    name: "Birria-Landia",
    category: "food",
    subcategory: "Mexican",
    address: "Various trucks",
    neighborhood: "Jackson Heights",
    description:
      "NYC’s most famous birria tacos. Rich consommé and crispy tortillas.",
    price_tier: 1,
    avg_price: 12,
    tags: ["birria", "food-truck"],
    lat: 40.744,
    lng: -73.88,
    status: "approved",
  },
  {
    id: "alys-trinbago",
    name: "Ali's Trinbago Roti Shop",
    category: "food",
    subcategory: "Caribbean",
    address: "1267 Fulton St",
    neighborhood: "Bed-Stuy",
    description: "Trinidadian roti and curry. Huge portions and bold flavor.",
    price_tier: 1,
    avg_price: 10,
    tags: ["roti", "caribbean"],
    lat: 40.6803,
    lng: -73.949,
    status: "approved",
  },
];
